name: Build Windows & macOS Executables

on:
  push:
    branches:
      - main  # 或你的分支名，比如 master
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 推荐 3.8 ~ 3.11，PyQt5 兼容性较好

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5
          pip install pyinstaller
        shell: bash

      - name: Build with PyInstaller
        run: |
          echo "Running PyInstaller on ${{ runner.os }}..."
          pyinstaller --onefile --windowed --icon=app_icon.icns large_text_comparator.py --name "LargeTextComparator"
        shell: bash

      - name: Show dist contents
        run: |
          echo "Contents of dist/:"
          ls -lh dist/
        shell: bash

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: large-text-comparator-${{ runner.os }}
          path: dist/LargeTextComparator*